#!/bin/bash

CONFIG="$HOME/.config/"

# Backup existing files
echo "Creating backup of existing files..."
backup_dir="$HOME/dotfiles_backup"
mkdir -p "$backup_dir/.config"
mkdir -p "$backup_dir/.local/share"

backup_if_exists() {
    if [ -d "$1" ]; then
        cp -rf "$1" "$backup_dir/"
    fi
}

backup_if_exists "$HOME/.oh-my-zsh"
backup_if_exists "${CONFIG}/i3"
backup_if_exists "${CONFIG}/alacritty"
backup_if_exists "${CONFIG}/nvim"
backup_if_exists "$HOME/.local/share/nvim"

clear

# Install dependencies
echo "Installing dependencies..."
sudo pacman -S zsh npm alacritty neovim ttf-0xproto-nerd
clear

# Install zsh
if [ ! -d "$HOME/.oh-my-zsh" ]; then
    sh -c "$(curl -fsSL https://raw.githubusercontent.com/ohmyzsh/ohmyzsh/master/tools/install.sh)" "" --unattended
fi
if [ ! -f "$HOME/.zshrc" ]; then
    rm -f ~/.zshrc
fi

# Install omz AutoSuggestions and VSCode plugins
git clone https://github.com/zsh-users/zsh-autosuggestions ${ZSH_CUSTOM:-~/.oh-my-zsh/custom}/plugins/zsh-autosuggestions
git clone https://github.com/valentinocossar/vscode.git ~/.zsh/vscode

chsh -s /bin/zsh
cp -f .zshrc $HOME/

# Install nvchad config
if [ -d "${CONFIG}/nvim" ]; then
    rm -rf "${CONFIG}/nvim"
    rm -rf "$HOME/.local/share/nvim"
fi
git clone https://github.com/NvChad/NvChad ~/.config/nvim --depth 1
nvim

cp -f .config/nvim/init.lua ${CONFIG}/nvim/init.lua

# Install vim plug for Neowim
sh -c 'curl -fLo "${XDG_DATA_HOME:-$HOME/.local/share}"/nvim/site/autoload/plug.vim --create-dirs \
       https://raw.githubusercontent.com/junegunn/vim-plug/master/plug.vim'

# Install vim config
cp -f ./.vimrc $HOME/

# Install alacritty
if [ -d "${CONFIG}/alacritty" ]; then
    rm -f "${CONFIG}/alacritty/alacritty.toml"
fi
mkdir -p "${CONFIG}/alacritty"
cp -f ".config/alacritty/alacritty.toml" "${CONFIG}/alacritty"

cp -rf .wallpaper $HOME/
clear

echo "Backup files are stored in ~/dotfiles_backup"
echo "Done ! Please restart your pc."
