#!/bin/bash

backup_dir="$HOME/dotfiles_backup"

if [ -d "$backup_dir" ]; then
    echo "Restoring backup..."

    restore_if_exists() {
        if [ -d "$backup_dir/$1" ]; then
            cp -rf "$backup_dir/$1" "$HOME/"
        fi
    }

    restore_if_exists ".oh-my-zsh"
    restore_if_exists ".config/i3"
    restore_if_exists ".config/alacritty"
    restore_if_exists ".config/nvim"
    restore_if_exists ".local/share/nvim"

    echo "Backup restored."
else
    echo "No backup files found."
fi
